### ISSUE TITLE
Can't update Team in `channelUpdate()`

### ISSUE THREAD

**Issue by inic07** [GetStream/stream-chat-swift#2628]
## What did you do?
I encountered while attempting to update a channel using the GetStream SDK.

I want to update the channel name and channel image.

As per the documentation provided in the GetStream SDK documentation for iOS Swift (https://getstream.io/chat/docs/ios-swift/channel_update/?language=swift), I tried using the mentioned method for updating the channel. However, upon calling this method, I encountered an error that prevented the channel from being updated successfully.

## What did you expect to happen?
Here Sample Code :

```
func updateChannel(_ name: String) {
    channelPass?.updateChannel(name: name, imageURL: nil, team: channelPass?.cid?.id) { error in
        if let error = error {
            print(error.localizedDescription)
        } else {
            print("Update Channel")
        }
    }
}
```

## What happened instead?
Output what I got:

```
 API request failed with status code: 403, code: 17 response:
{
  "code" : 17,
  "message" : "UpdateChannel failed with error: "changing channel team is not allowed client-side"",
  "more_info" : "https://getstream.io/chat/docs/api_errors_response",
  "details" : [

  ],
  "StatusCode" : 403,
  "duration" : "0.00ms"
})

```

## GetStream Environment
**GetStream Chat version: *4.30.0*
**GetStream Chat frameworks: ** StreamChat, StreamChatUI
**iOS version: *15*
**Swift version: *5.0*
**Xcode version: *14.0.1 (14A400)*
**Device: *iPhoneX*

**Comment by nuno-vieira** [comment]
Hi, @inic07!

It looks like you found an issue in the iOS SDK. As the message says in that response, our API does not allow changing the teams on the client-side SDKs, only on the server side. So we will need to remove this on the iOS SDK.

What are you using the teams feature for? What is your use case? You can read more about how the teams feature works here: https://getstream.io/chat/docs/react/multi_tenant_chat/?language=swift

Make sure your use case is related to Multi Tenancy, if not, maybe you can use extra data for your use case. 

Thank you for the report. We will remove this property from `updateChannel`.

Best,
Nuno

**Comment by inic07** [comment]
Hello @nuno-vieira ,

Thank you for your response. I apologize for the confusion caused by the issue in the iOS SDK.

Regarding the teams feature, our use case is not related to Multi Tenancy. We are not utilizing the teams feature for our application. Instead, we are using custom logic and extra data to handle our specific use case.

 I am writing to seek your guidance and assistance regarding the process of modifying the "updateChannel" function to update the name or image of a channel. As an active user of your platform, I believe this information will greatly enhance my understanding and utilization of the features available.

I have been exploring the functionalities of your platform and have come across the "updateChannel" function, which allows users to make changes to existing channels. However, I am uncertain about how to go about modifying the channel name or image using this function. I would greatly appreciate it if you could provide me with some guidance or instructions on achieving this.

If there are any specific parameters or arguments that need to be included in the "updateChannel" function to accomplish these modifications, please provide the necessary details. Additionally, if there are any prerequisites or considerations that I should be aware of before making these changes, kindly inform me.

Your expertise in this matter would be of immense help, as it would enable me to make necessary updates to the channels I manage. I am eager to make the most of your platform's capabilities and ensure that my channels are up-to-date and visually appealing.

Thank you once again for your assistance.

Best,
Nikunj

**Comment by nuno-vieira** [comment]
Hi @inic07,

You do not have to apologize, but we do since it is our mistake 🙂 

In your code, for now, you need to provide `team: nil` in order for the update to work. Here is what you need to do:

```swift
func updateChannel(_ name: String) {
    channelPass?.updateChannel(name: name, imageURL: nil, team: nil) { error in
        if let error = error {
            print(error.localizedDescription)
        } else {
            print("Update Channel")
        }
    }
}
```

Best,
Nuno

**Comment by inic07** [comment]
Thank you for your quick support @nuno-vieira  and for addressing my previous inquiry. I appreciate your clarification regarding the code and the required parameter for updating the channel.

However, I am still eager to know if the "updateChannel" function supports multipart requests for uploading an image for the channel. Could you please provide me with more information on this matter? If there is a way to include an image upload in the update process, I would like to learn how to implement it correctly.

**Comment by inic07** [comment]
Thank you @nuno-vieira for your  support

**Comment by inic07** [comment]
Hello @nuno-vieira 

I kindly request your assistance once again. I have a query regarding the creation of a user with a custom field, as shown in the attached screenshot. The custom fields I am referring to are GroupID and OperatorID, which are based on comma-separated strings.

<img width="520" alt="Screenshot 2023-05-22 at 12 15 45 PM" src="https://github.com/GetStream/stream-chat-swift/assets/69636497/f3d962b7-db21-490d-a7b2-11a91e0d0da0">


Currently, I am experiencing some issues with the results of the query I have made using these custom parameters. Could you please let me know if using comma-separated values in the custom field is the correct approach, as the expected results are not being generated as intended? Your help in resolving this matter would be greatly appreciated.


```
if let groupID = UserManager.shared.current?.groupID, !groupID.isEmpty {
        let query = UserListQuery(
            filter: .or([
                .in(.operatorID, values: ["\(opID)"]),
                .in(.groupID, values: [groupID])
            ]),
            sort: [.init(key: .lastActivityAt, isAscending: true)],
            pageSize: 20
        )
        
        searchController.search(query: query) { error in
            if error != nil {
                self.update(for: .error)
            }
        }
    }
```

**Comment by nuno-vieira** [comment]
Hi @inic07,

How are you inserting that data? Looking at the dashboard, it seems that you are adding it as a string, instead of an array. You need to update those properties as arrays, so that the query you are performing works.

Best,
Nuno

**Comment by inic07** [comment]
Yes @nuno-vieira by adding it in array form,   it working fine now.

**Comment by inic07** [comment]
hi @nuno-vieira , 

I am facing an issue with push notifications on my system.

Even after logging out from my system, I receive a push notification. I have implemented the following functions to handle push notifications disable/disconnect channel.(i tried all 3 function)

```

func removeCurrentDevice() {
    if let chatClient = self.client {
        guard let deviceId = chatClient.currentUserController().currentUser?.currentDevice?.id else {
            return
        }
        chatClient.currentUserController().removeDevice(id: deviceId) { error in
            if let error = error {
                log.warning("Removing the device failed with an error: \(error)")
            }
        }
    }
}

func removeDevice() {
    if let chatClient = self.client {
        guard let deviceId = chatClient.currentUserController().currentUser?.devices.last?.id else {
            return
        }
        chatClient.currentUserController().removeDevice(id: deviceId) { error in
            if let error = error {
                log.warning("Removing the device failed with an error: \(error)")
            }
        }
    }
}

func logout() {
    removeCurrentDevice()
    if let chatClient = self.client {
        chatClient.logout {
            // Additional code for logout completion
        }
    }
}

```

Sometimes I got errors like below :
```

{
  "code" : 5,
  "message" : "DeleteDevice failed with error: "stream-auth-type missing or invalid"",
  "details" : [

  ],
  "more_info" : "https://getstream.io/chat/docs/api_errors_response",
  "StatusCode" : 401,
  "duration" : "0"
})
```

Did I implement it correctly, or did I miss something?

**Comment by nuno-vieira** [comment]
Hi @inic07!

You need to wait for the removeDevice call, and only then you can logout, something like this:

```swift
let currentUserController = client.currentUserController()
if let deviceId = currentUserController.currentUser?.currentDevice?.id {
   currentUserController.removeDevice(id: deviceId) { error in
        if let error = error {
             log.warning("removing the device failed with an error \(error)")
        }
        client.logout(completion: completion)
    }
}
```

But, in fact, the `logout()` function should do this out of the box, it should remove the current device. Can you open an issue here on Github? 🙏  Something like "Still receive push notifications after logging out" 

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi @inic07!

Sorry, after talking with the team I found that this is on propose. Either way, we will improve the docs around this 👍 

https://github.com/GetStream/stream-chat-swift/issues/2641#issuecomment-1559066091

**Comment by inic07** [comment]
So @nuno-vieira 

How can I disable notifications for a user when they sign out of our system? 

While we can handle Global Platform notifications it appropriately, our system manages user sessions based. I need to ensure that notifications are no longer sent to users who have signed out. What is the recommended approach to achieve this?

**Comment by nuno-vieira** [comment]
Hi @inic07!

The solution is mentioned here: https://github.com/GetStream/stream-chat-swift/issues/2628#issuecomment-1559042998

You need to call logout() inside the `removeDevice()` completion. Then, it will work as you expect it 👍

**Comment by polqf** [comment]
Hi @inic07 , I am closing this ticket due to inactivity
