### ISSUE TITLE
`.joined` channel filter doesn't seem to be working

### ISSUE THREAD

**Issue by brianmwadime** [GetStream/stream-chat-swift#2669]
## What did you do?
Used the filter below with `channelListController`
```
let controller = ChatClient.shared.channelListController(query: .init(
            filter: .and(
				[
					.in(.type, values: [.custom("public")]),
					.equal(.joined, to: false)
				]
			),
            sort: [.init(key: .default, isAscending: false)]
        ))
```

## What did you expect to happen?

Expected it to return public type channels that I am not a member of.

## What happened instead?

Doesn't return the public I haven't joined.

## GetStream Environment
**GetStream Chat version:** 4.32.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 16.3.1
**Swift version:** 5
**Xcode version:** 14.3.1
**Device:** iPhone 8

**Comment by polqf** [comment]
Hi @brianmwadime ,

You said that you are using 4.32.1, but this version does not exist.
Your issue seems to be the same one that was fixed [here](https://github.com/GetStream/stream-chat-swift/pull/2634), which was shipped as part of release 4.32.0

Could you try to upgrade to the latest version (4.33.0 as of now) and confirm if the issue is still there?

**Comment by brianmwadime** [comment]
Hi @polqf my mistake. Corrected to `4.32.0`. I had tried the latest version `4.33.0` first then downgraded to `4.32.0`.
It still didn't work on both.

We also add users using either the  `members` prop when creating a channel and through the `addMembers` function.

**Comment by polqf** [comment]
Hi @brianmwadime ,

I misread your initial message thinking that you were using .joined as true. But instead, you are trying to get the channels where the user is not present.

You might not be able to fetch such channels if the user does not have permission to read those.
For example, by default, a `livestream` channel type allows anyone to read it, so you will get such channels when fetching non-joined channels.

**Comment by brianmwadime** [comment]
Hi @polqf,

If I remove the .joined filter completely the user can see channels that they are a member of and also those they aren't.

Does this mean .joined is restricted by permissions? (NB: Our public channels are accessible to all users whether joined or not)

And is there a different way to get only the a user isn't a member of?

**Comment by brianmwadime** [comment]
> Hi @brianmwadime ,
> 
> I misread your initial message thinking that you were using .joined as true. But instead, you are trying to get the channels where the user is not present.
> 
> You might not be able to fetch such channels if the user does not have permission to read those. For example, by default, a `livestream` channel type allows anyone to read it, so you will get such channels when fetching non-joined channels.

Hello @polqf ,
Confirming that we had been giving user the *read-channel* and *read-channel-members* permissions for our public channels. But we still can't use the filter as stated above.

**Comment by brianmwadime** [comment]
Hello @polqf ,
Which permission do we give users to be use the *joined* filter?

**Comment by testableapple** [comment]
Hi @brianmwadime,
To learn more about permissions, please refer to [these docs](https://getstream.io/chat/docs/other-rest/user_permissions/).

In regards to your issue, it sounds like you should use the `livestream` channel type, as @polqf mentioned in the comment above as example. Please let us know the channel type that you use.
If nothing helps, I'd recommend changing your query and fetching all public channels.

Best,
Alexey

**Comment by brianmwadime** [comment]
Hello @testableapple ,
We've gone through the permissions and thought `read-channels` and `read-channel-members` would let a user be able to filter channels by membership, which seems to not be the case.

We are using a custom channel type `Public` for channels that any user can join. We want to fetch channels that a user is not a member `.joined` = false

**Comment by brianmwadime** [comment]
Oherwise it seems the `.joined` filter is buggy.

**Comment by testableapple** [comment]
The problem is that fetching channels you are not a member of is not possible if the channels are not livestreams.
So the question is, are you able to fetch all the public channels (where the user IS and IS NOT a member)? If so, then filtering the whole list with `.joined == false` should potentially work.

**Comment by brianmwadime** [comment]
Yes, we are able to fetch all the public channels.

**Comment by brianmwadime** [comment]
Which permission allows a user to fetch livestreams they aren't a part of so we can use it as well on our public channels?

**Comment by brianmwadime** [comment]
Also we can use `.joined` = true and we get the public channels the user has joined, only `.joined` = false fails in our case.

**Comment by testableapple** [comment]
Please take a look at the [permissions reference doc](https://getstream.io/chat/docs/ios-swift/permissions_reference/ ) (scroll to `Scope video:livestream`) to compare the permissions you have in your custom channel type with the default ones in livestream.

**Comment by brianmwadime** [comment]
@testableapple the perms are okay on our public groups. Going through the sdk tests I noticed there's only one test for `.joined` = true only.
Was this filter not supposed to work for scenarios that would require `.joined` = false ?

**Comment by nuno-vieira** [comment]
@brianmwadime The test also works for the false case as well. The reason there's no test for that is because it is a bit redundant in this case. Either way, I double-checked and wrote the following test, and it worked:

```swift
        let cid1 = ChannelId.unique
        let cid2 = ChannelId.unique

        try assertFilterPredicate(
            .equal(.joined, to: true),
            channelsInDB: [
                .dummy(channel: .dummy(cid: cid1)),
                .dummy(channel: .dummy(team: .unique), membership: .dummy()),
                .dummy(channel: .dummy(team: .unique), membership: .dummy()),
                .dummy(channel: .dummy(team: .unique), membership: .dummy()),
                .dummy(channel: .dummy(cid: cid2)))
            ],
            expectedResult: [cid1, cid2]
        )
```

Best,
Nuno

**Comment by brianmwadime** [comment]
@nuno-vieira yeah, tried that as well and the test case worked.
