### ISSUE TITLE
Pin Message behavior

### ISSUE THREAD

**Issue by ondrejkorol** [GetStream/stream-chat-swift#2697]
## What did you do?
I'm trying to pin various messages and I discovered that not all messages are properly pinned and saved on the server:
- only text ✅
- text message containing URL ❌
- text message containing a photo ❌
- only URL ❌
- only photos ❌

## What did you expect to happen?
I'd expect no matter what's the content of the message, it should be pinned and stored on the server, so other people can see these messages as pinned. Those messages should contain `pinned_at` and `pinned_by` properties.

## What happened instead?
Pins for messages that aren't text only are saved **only locally**, but not synced to the server, so other users can't see those pinned messages. You can see this behavior via Chat Explorer, or even in the Demo app (when switching the account).

## GetStream Environment
**GetStream Chat version:** 4.33
**GetStream Chat frameworks:** StreamChat, StreamChatUI 4.33/main
**iOS version:** 15 – 16.5
**Swift version:** 5
**Xcode version:** 14.3.1
**Device:** doesn't matter

## ⚠️ Additional issue: ##
Moreover, it seems that `channel.pinnedMessages` isn't a reliable way how we can retrieve pinned messages. Sometimes it won't return any message, sometimes all of them or only a few of them. That's also visible in the demo app as well (try to open a DM channel with pinned messages -> tap the avatar -> pinned messages .. it's 50:50 you will see pinned messages or empty state; return to the chat list and repeat)

**Comment by nuno-vieira** [comment]
Hi @ondrejkorol!

Thank you for the report! 

This is indeed an issue introduced on 4.33.0. If you can, you can rollback to 4.32.0 until we fix this issue. 

Meanwhile, we will work on this one soon and will let you know once we have it fixed 👍 

Best,
Nuno

**Comment by ondrejkorol** [comment]
Aah, great! I'm happy it's a known bug that will be addressed.
Thank you so much for the info!

**Comment by ondrejkorol** [comment]
I can see the fix has been merged – that was so fast, thank you!
And also thank you for the suggestion to create another issue – I'll investigate it more and eventually create it.

**Comment by ondrejkorol** [comment]
@nuno-vieira 
One observation I have.. it seems like **pinned** messages currently "lose" reactions in case there are multiple of them (e.g. liked by 2 users). Or they sometimes disappear, and after a while, they appear..
Do you think the merged change would fix this as well? It's reproducible in Stream Demo app -> pin message, react, change the account, and react to that message as well.
Or should I start a new issue?

**Comment by testableapple** [comment]
Hi @ondrejkorol,
This has been fixed in our latest release [4.35.1](https://github.com/GetStream/stream-chat-swift/releases/tag/4.35.1).
Closing this issue for now, feel free to reopen it if you encounter any issues.

**Comment by nuno-vieira** [comment]
@ondrejkorol Make sure to re-test that Pinned issue as well. If you can reproduce it still, please re-open a new ticket so that we can analyse further 👍

**Comment by ondrejkorol** [comment]
@nuno-vieira Thank you for letting me know, I updated the SDK to 4.35.1 and it looks great! Images and URLs are properly pinned and other users can see them.
Thank you so much!

(I'll open another issue regarding the reactions of pinned messages... this seems like it's still broken)
