### ISSUE TITLE
Input is too high when chat is presented in UITabBarController

### ISSUE THREAD

**Issue by mpodeszwa** [GetStream/stream-chat-swift#28]
## What did you do?

I present Chat inside UITabBarController

## What did you expect to happen?

Input is right above keyboard

## What happened instead?

Input is offset from the keyboard (probably by tabbar's height)

## Additional context

Device: Iphone 11

I created branch to show the problem:
https://github.com/mpodeszwa/stream-chat-swift/tree/bugfix/tab-input-offset

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-03 at 12 56 34](https://user-images.githubusercontent.com/7826664/66121500-a4fba880-e5dd-11e9-883c-08236b0f77a8.png)

**Comment by buh** [comment]
Thanks! I'll check.

**Comment by Spenser** [comment]
We are also experiencing this as well

**Comment by buh** [comment]
Hi guys, it should be fixed in the last release.
Let me know if it still there.

**Comment by mpodeszwa** [comment]
Hi @buh ,
It's almost fixed :) It works if tab bar is translucent, but if this flag is turned off then problem is still there. I rebased my branch, you can check it out https://github.com/mpodeszwa/stream-chat-swift/tree/bugfix/tab-input-offset

**Comment by buh** [comment]
Fixed in the next version 1.4.0.

**Comment by mpodeszwa** [comment]
Hi @buh ,
I checked out `master` and unfortunately I don't think it's completely fixed.
This is how chat looks without the tab bar:
![without tab](https://user-images.githubusercontent.com/7826664/68074439-4de32200-fd9b-11e9-87c7-4799f6e56750.png)
And with the tab bar:
![with tab](https://user-images.githubusercontent.com/7826664/68074442-55a2c680-fd9b-11e9-9b38-db27c5f4ce43.png)


I was testing on iPhone 11 Pro Max. I rebased my branch again https://github.com/mpodeszwa/stream-chat-swift/tree/bugfix/tab-input-offset 😄

**Comment by mpodeszwa** [comment]
Hi @buh 
After fixing #36 this bug reappeared 😭  #36 is now fixed :)

**Comment by mpodeszwa** [comment]
rebased once more https://github.com/mpodeszwa/stream-chat-swift/tree/bugfix/tab-input-offset :D

**Comment by buh** [comment]
That's weird. Thanks! I'll check

**Comment by buh** [comment]
@mpodeszwa  Do you mean #28 was fixed?

**Comment by mpodeszwa** [comment]
I thought in 1.5.0 #28 was fine and #36 appeared and now in 1.5.1 it's the opposite. To be honest I'm not 100% sure if #28 was fixed earlier 🤔

**Comment by buh** [comment]
It was fixed, I used some hack to save additional offset with tabbar height.
But anyway on elf our customer has another bug, that I couldn't reproduce and it was really annoying to fix. So, I decide to rewrite the Composer view position in new way. It much more simple and easy to manage. I'm checking why it doesn't work for you.

**Comment by buh** [comment]
It's fixed v.1.5.3
Your ChatViewController should be embedded properly. The parent view controller at least should have correct `safeAreaInsets`.

I recommend you to use `UIContainerView` to embed it properly. Here is my example that works:
![Screenshot 2019-11-27 at 15 20 47](https://user-images.githubusercontent.com/284922/69732524-0d718c80-112c-11ea-9347-7f9efc9f5904.jpg)

**Comment by mpodeszwa** [comment]
Hi @buh 
Unfortunately it doesn't work for me. I tried using `UIContainerView` but it's still the same. Can you check out this branch? 
https://github.com/mpodeszwa/stream-chat-swift/tree/bugfix/tab-input-offset

**Comment by buh** [comment]
Can't make a commit in your fork.
Please update Main.storyboard with this:
[Main.storyboard.zip](https://github.com/GetStream/stream-chat-swift/files/3898251/Main.storyboard.zip)

**Comment by mpodeszwa** [comment]
Thanks for quick response, I downloaded your storyboard and it works, but only with translucent tab bar. If I turn this flag off, the input goes higher :/ I can't really turn on translucent tab bar on my app, because it doesn't go well with our designs :( 
<img width="816" alt="Screenshot 2019-11-27 at 19 46 17" src="https://user-images.githubusercontent.com/7826664/69751237-f728f800-114e-11ea-8177-723ff30a170b.png">
![Simulator Screen Shot - iPhone 8 Plus (iOS 11 4) - 2019-11-27 at 19 46 37](https://user-images.githubusercontent.com/7826664/69751263-05771400-114f-11ea-95c2-340cbd6c5641.png)

I checked on iPhone 8 Plus with iOS 11.4

**Comment by buh** [comment]
@mpodeszwa ok I’ll think how to fix it

**Comment by buh** [comment]
Please check `master` with the fix.

**Comment by mpodeszwa** [comment]
Awesome, works great now :) Thanks 👍
