### ISSUE TITLE
Unable to get push notification

### ISSUE THREAD

**Issue by saurabhPV** [GetStream/stream-chat-swift#84]
## What did you do?

1. Open the app.
2. Allowed pushed via permission pop up.
3. Closed the app.
4. Waited for 5 mins (so client get disconnected  https://github.com/GetStream/stream-chat-swift/issues/31#issuecomment-547977944 )
5. Sent the message from another device.

## What did you expect to happen?
I was expecting a push notification

## What happened instead?
Didn't get any push

## GetStream Environment
**GetStream Chat version:**  1.5.4
**iOS version:** 13.3
**Swift version:** 5
**Xcode version:** 11.3.1
**Device:** iPhone x

## Additional context

I was using different keys  but didn't get any push so I tried using the different keys.
But no luck.
On stream dashboard under push logs it says 
`publishing the message failed with error: InvalidProviderToken`

On log details I found the push token and I was able to send push using that token using a push test utility I found on web.

**Comment by saurabhPV** [comment]
I apologise for badgering you guys, I am evaluating product for our client and this is probably the last issue I have discovered.

**Comment by buh** [comment]
Hey @saurabhPV can you confirm you added the device token to Stream? Did you add a push notification template in our dashboard?

Please check this doc: https://github.com/GetStream/stream-chat-swift/wiki/Push-Notifications

**Comment by saurabhPV** [comment]
Yes , I am using an example app and  I can see in AppDelegate

```
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        print("🗞📱", "App did register for remote notifications with DeviceToken")
        
        Client.shared.addDevice(deviceToken: deviceToken)
            .subscribe()
            .disposed(by: disposeBag)
    }

```
And template on dashboard

```

{
    "aps" : {
        "alert" : {
            "title" : "{{ sender.name }} @ {{ channel.name }}",
            "body" : "{{ message.text }}"
        },
        "badge": {{ unread_count }},
        "category" : "NEW_MESSAGE"
    }
}
```

Besides I can also see token in push log 

<img width="549" alt="Screenshot 2020-01-31 at 5 01 36 PM" src="https://user-images.githubusercontent.com/15213067/73536203-78e91a80-444b-11ea-9c09-eb57a1556843.png">

I can send push to this app using this token.

**Comment by saurabhPV** [comment]
I tried using different apple account key new bundle id new app in GetStream but no luck. I am still not getting any push. 
And as earlier I can get the push for this app (using same credentials and token) via a testing tool.

On GetStream I am using develop mode hope that doesn't affect in any way.

**Comment by b-onc** [comment]
@saurabhPV `InvalidProviderToken` means there's an error while setting up the push notifications. Can you make sure everything is setup correctly? Can you try with a physical device?

**Comment by saurabhPV** [comment]
of course I have been trying with physical devices since push is not supported on iOS  simulator.

And I am sure everything is correct on client side because otherwise there is no explanation why  I can send a push notification from a testing tool using the device id I retrieved from the GetStream dashboard. 
If there is a token in the log that necessary means  token was retrieved by the app and was successful in posting that to GetStream backend as well. I don't think there is anything further that needs to be done from client side.

There is only one other possibility that I have provided wrong details on dashboard but I am using the correct details in the testing tool! To eliminate even that I created new app in GetStream , used entirely different  Apple account and keys and the results were same, no push in GetStream but got push from the testing tools for same device token.

**Comment by buh** [comment]
I asked our backend team, `InvalidProviderToken` means Push Notification Certificate is not valid. Can you check you uploaded the right certificate on our dashboard?

**Comment by saurabhPV** [comment]
I thought so too and like I said in my earlier comments I have tried using 4 different keys from 2 different accounts. Results are same.
Is it possible to retrieve key in the backend logs? 
I have uploaded p8 file = `AuthKey_YMGZ27N69H.p8`
Certificate is `MIGTAgEAMBMGB..... 3HEyHGek `
I am using this file and I can get push in the app with an online push testing tool.

**Comment by b-onc** [comment]
Hello @saurabhPV ,
Which testing tool are you using?

**Comment by saurabhPV** [comment]
https://www.logisticinfotech.com/send-push-notification-online/
Please let me know if  you need any other details.

**Comment by saurabhPV** [comment]
if you prefer here is an [open source](https://github.com/onmyway133/PushNotifications) app that I have been using.
@b-onc

**Comment by saurabhPV** [comment]
Thank you so much to all of you guys for your incredible support!

App id is 67851 - werq-team-chat-v2

Yes this is configured for both Firebase and APNS notifications. {Yes we are having issues in Firebase too } 

You can use either tool. First one is convenient , if you don't like uploading certificate on website (like me😉) you might like latter.

You can procure certificate from my account? If not could you please share your email me so I can share that file ? My email id is Saurabh_Patil@in.nisostech.com 

(I tried  https://getstream.io/support  but could not find an option to upload file)

Please let me know if you need any details or if you need we can debug real time too.

**Comment by b-onc** [comment]
Hello @saurabhPV , just wanted to let you know that we're able to replicate this issue and working on a fix.

**Comment by saurabhPV** [comment]
Thank you @b-onc for the update. By any chance will you be able to let me know when can this be fixed. I need to advice my client if he should opt this product.

**Comment by tbarbugli** [comment]
@saurabhPV a patch for this problem is going live tomorrow

**Comment by saurabhPV** [comment]
Hello @tbarbugli , do I need to do any changes on client side ? Because I still haven't seen push notifications for the messages I sent today.

**Comment by buh** [comment]
@saurabhPV did you test pushes with our cli tool?

**Comment by saurabhPV** [comment]
No I have sent few messages today and I can see in the push log, same error
`publishing the message failed with error: InvalidProviderToken`

**Comment by buh** [comment]
I know it was a bug on our Dashboard. Can you submit your .p12 or other push certificate in our Dashboard and try again?

**Comment by saurabhPV** [comment]
I get push now however they are not consistent, it keeps dropping almost one in three and error message still doesn't reflect the real error , I believe.

In the logs I can see first it was success then fail and again success <img width="1209" alt="Screenshot 2020-02-19 at 4 52 55 PM" src="https://user-images.githubusercontent.com/15213067/74830321-dda3e080-5338-11ea-81b7-1771491805ff.png">

Here is the log that says token is incorrect 

<img width="596" alt="Screenshot 2020-02-19 at 4 53 07 PM" src="https://user-images.githubusercontent.com/15213067/74830494-49864900-5339-11ea-8511-e3988baf7a66.png">

but the very next message just after few seconds, it was able to send the push

<img width="579" alt="Screenshot 2020-02-19 at 4 53 20 PM" src="https://user-images.githubusercontent.com/15213067/74830486-43906800-5339-11ea-871c-7861c3a8c403.png">

**Comment by buh** [comment]
Did you wait a minute for the app in the background for the connection was closed? We need to isolate the problem. You can enable logs and will see when the connection was closed and send a message.
Please update our SDK to 1.5.7. It has several fixes, that could be related to your case.

**Comment by saurabhPV** [comment]
I am using 1.5.7 now and it seems I am getting push pretty much regularly, however there are certain occasions where I think I have missed it. I will test it for few more days and will let you know.

Thank you so much guys!!!

**Comment by saurabhPV** [comment]
Push are not reliable. I usually miss it for sporadic messages and once I send 3-4 messages then it sends one and at the same time I get the message from my server. It is invoked using the get stream  web hook.

**Comment by buh** [comment]
Hi, @saurabhPV 
Thanks for your message!
Can you tell me what is your SDK version? Please update it to 1.5.7 it has some fixes that should fix this issue.

**Comment by saurabhPV** [comment]
I did, https://github.com/GetStream/stream-chat-swift/issues/84#issuecomment-589619377 , and I started getting push, with 1.5.5 I miss every push but with 1.5.7 I get push but not consistently.

**Comment by buh** [comment]
We need to figure out where is the problem:
1. If you are testing when the app just moved to the background, then local notifications probably won't work and there needs to check how you setup it.
2. If it a case when your app in the background more then 2 min and you didn't get a push, then probably something on our backend.

Please check the docs again. Is it possible for you to miss something?
https://github.com/GetStream/stream-chat-swift/wiki/Push-Notifications

**Comment by saurabhPV** [comment]
I always get local push. It's the server push that's not reliable.

**Comment by buh** [comment]
@saurabhPV Our backend is working on a fix. It will be done this week, probably tomorrow. I'll keep you updated.

**Comment by saurabhPV** [comment]
ok thanks. Let me know if you guys need anything further.

**Comment by buh** [comment]
@saurabhPV this issue should be fixed now. Can you check?

**Comment by shireeshMs** [comment]
Hello team,
I have registered my device token to GetStream AddDevice Method for push notifications and got success (for referrence sending you the screenshot) but still on server it is saying no device found .
Please help me out 

<img width="1680" alt="Screenshot 2020-03-13 at 6 51 42 PM" src="https://user-images.githubusercontent.com/37240061/76625376-195b5000-655d-11ea-93bc-f0e22d56e8b3.png">

<img width="1149" alt="Screenshot 2020-03-13 at 6 56 52 PM" src="https://user-images.githubusercontent.com/37240061/76625371-17918c80-655d-11ea-8405-78e553aaf75d.png">

**Comment by bogdan-getstream** [comment]
Hi @shireeshMs 
I'm seeing that device was added successfully for user with id `1016`

```
user@laptop ~ % stream chat:push:device:get
✔ What is the User ID? · 1016
┌──────────────────────────────────────────────────────────────────┬───────────────┐
│ Device ID                                                        │ Push provider │
├──────────────────────────────────────────────────────────────────┼───────────────┤
│ 1f5ae00031c4c6705375dbd54b0e4c190fc8666c68fba0ea5bab13ec2ca27160 │ apn           │
└──────────────────────────────────────────────────────────────────┴───────────────┘
```

**Comment by ronnieguha** [comment]
This problem is back as of today.

![image](https://user-images.githubusercontent.com/2109530/76638559-0461cb00-6523-11ea-8259-f743cb3454c5.png)

**Comment by bogdan-getstream** [comment]
@ronnieguha 
Please, describe the problem.
`BadDeviceToken` is correct response from Apple servers which means that device id is not valid.
Probably you are using development build; but development endpoint is set to `no` as you see on the screenshot

**Comment by bogdan-getstream** [comment]
If you haven't installed application from app store - development should be set to true

**Comment by ronnieguha** [comment]
I installed it from hockeyapp/appcenter which uses the adhoc profile.. I even tried setting development to true as well, ... no go.

**Comment by bogdan-getstream** [comment]
@ronnieguha currently we are supporting only production and development builds for push notifications. That's a reason why you are having BadDeviceToken, as ad-hoc profile use different push endpoint

**Comment by ronnieguha** [comment]
Closing now. It started working
